### ISSUE TITLE
use a lookup in stead of a shell var in multiple-jumphosts

### ISSUE THREAD

**Issue by RobVerduijn** [IBM/IBMDeveloper-recipes#5]
regarding the multiple-jumphost-in-ansible-tower recipes

In the proxy-command you specify the shell environment variable $JH_SSH_PRIVATE_KEY
```
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -p {{ jh_ssh_port }} {{ jh_ssh_user }}@{{ jh_ip }} -i $JH_SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"'
```
I couldn't get that to work untill I replaced it with a lookup **lookup('env','JH_SSH_PRIVATE_KEY')**
```
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -p {{ jh_ssh_port }} {{ jh_ssh_user }}@{{ jh_ip }} -i {{ lookup('env', 'JH_SSH_PRIVATE_KEY') }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"'
```
also... for readability ( and reduce the quoting and escaping annoyance ) I added a little [yaml multiline magic](https://yaml-multiline.info/)
```
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand=" \
         ssh -W %h:%p -p {{ jh_ssh_port }} {{ jh_ssh_user }}@{{ jh_ip }} \
         -i {{ lookup('env', 'JH_SSH_PRIVATE_KEY') }} \
         -o StrictHostKeyChecking=no \
         -o UserKnownHostsFile=/dev/null"
```

Sadly I got it only to work with a password-less key, somehow tower 3.8.2 refused to apply the password from the credential.

Rob

**Comment by RobVerduijn** [comment]
forget the escape between the double quotes

**Comment by thinkahead** [comment]
1. You should not need to do a lookup because the process that Ansible Tower invokes for ssh to the endpoint should expand the environment variable with $JH_SSH_PRIVATE_KEY, but {{ lookup('env', 'JH_SSH_PRIVATE_KEY') }} works too!
2. You should be able to use the ssh credential with passphrase for the endpoint, but not for the custom jumphost credential in Part 1 and Part 2.
3. Jumphost credentials with passphrase are covered in later parts when expect script is used

**Comment by porben** [comment]
@thinkahead Alexi, this seems resolved. Is it ok to close it?
